#!/bin/bash
cd ./database/scripts/

echo $1
echo $2
echo $3
echo $4
echo $5
exit

if [[ $1 == *.svg ]]; then
    python3 svgtopng.py $1 $(echo $2 | cut -f 1 -d '.')
else
    cp $1 $(echo $2 | cut -f 1 -d '.')
fi

./data_pack.py $4 $(echo $2 | cut -f 1 -d '.')

if [ "$5" -eq -1 ]; then
    mv $5 $3/$5
fi
